#!/usr/bin/env bash
# the script displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=":" read -r name password id group_id user_id_info home_directory command;
do
	echo The user "$name" is part of the "$group_id" gang, lives in "$home_directory" and rides "$command". "$id"\'s place is protected by the passcode "$password", more info about the user here: "$user_id_info"
done < /etc/passwd
