#!/usr/bin/env bash
# the script displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
count=1;
while ((count < 11))
do 
	echo Best School;
	if((count == 9)); then echo Hi; fi
	((count+=1)); 
done

