#!/usr/bin/env bash
# the script displays the content of the current directory in a list format where only the part of the name after the first dash is displayed (refer to the example)
for file in *; do 
	echo  "$file" | cut -d- -f2-; 
done  
