#!/usr/bin/env bash
# the sript add its pid in the myscript.pid, display some text infinite, dislay text on SIGINT and SIGTERM, and delete the myscript.pid and exit the program on SIGTERM AND SIGQUIT.
echo $$ > /var/run/myscript.pid;
trap "echo I hate the kill command;rm /var/run/myscript.pid;exit 0" SIGTERM;
trap "echo Y U no love me?!" SIGINT;
trap "rm /var/run/myscript.pid;exit 0" SIGQUIT;
while ((2 > 1));
do
	echo To infinity and beyond;
done;
