#!/usr/bin/env bash
# The script displays To infinity and beyond indefinitely and display I am invincible!!! when receiving a SIGTERM signal.
trap "echo I am invincible!!!" SIGTERM
while ((1 > 0)); do
	echo To infinity and beyond;
	sleep 2;
done	
